use crate::backend::get_backend;
use crate::ensure_realtime_audio_thread;
use crate::resample_interleaved_linear;
use crate::protocol::parse_packet;
use crate::recording::{
    create_wav_writer, finalize as finalize_recording, generate_record_path, write_samples,
    SharedWavWriter,
};
use crate::util::safe_lock;
use crate::{register_scoped_signal_meter, SignalDirection};
use std::collections::VecDeque;
use std::net::UdpSocket;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use std::time::Duration;

pub fn receive_and_split_to_devices(
    bind_addr: &str,
    device_targets: Vec<Option<String>>,
    record_each_channel: bool,
    keep_running: Arc<AtomicBool>,
) -> Result<(), String> {
    ensure_realtime_audio_thread();

    let socket = UdpSocket::bind(bind_addr)
        .map_err(|error| format!("failed to bind {bind_addr}: {error}"))?;

    socket
        .set_read_timeout(Some(Duration::from_millis(200)))
        .map_err(|error| format!("failed to set read timeout: {error}"))?;

    println!(
        "Split-receive listening on {bind_addr}, waiting for \
         first packet..."
    );

    // The OpenAudio protocol supports up to 255 channels. At 58
    // Float32 frames per packet, a 65,536-byte receive buffer safely
    // accommodates the largest packet currently generated by the
    // non-ASIO publishers.
    let mut packet_buffer = [0u8; 65_536];

    let (channel_count, sample_rate, first_payload_offset, first_packet_length) = loop {
        if !keep_running.load(Ordering::Relaxed) {
            return Ok(());
        }

        match socket.recv_from(&mut packet_buffer) {
            Ok((packet_length, _source)) => {
                if let Some(parsed) = parse_packet(&packet_buffer[..packet_length]) {
                    break (
                        parsed.channel_count as usize,
                        parsed.sample_rate,
                        parsed.payload_offset,
                        packet_length,
                    );
                }
            }
            Err(ref error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                continue;
            }
            Err(ref error) if error.kind() == std::io::ErrorKind::TimedOut => {
                continue;
            }
            Err(ref error) if error.kind() == std::io::ErrorKind::ConnectionReset => {
                continue;
            }
            Err(error) => {
                return Err(format!(
                    "recv error while waiting for first packet: \
                     {error}"
                ));
            }
        }
    };

    if channel_count == 0 {
        return Err("incoming split stream has zero channels".to_string());
    }

    println!("Detected {channel_count}ch @ {sample_rate}Hz.");

    if device_targets.len() != channel_count {
        return Err(format!(
            "got {} device target(s) but the incoming stream \
             has {channel_count} channel(s) -- these must match \
             exactly",
            device_targets.len()
        ));
    }

    // One meter channel represents one logical incoming network
    // channel, regardless of how many hardware channels the selected
    // output device uses.
    let (signal_meter, _signal_meter_guard) = register_scoped_signal_meter(
        format!("split-output:{bind_addr}"),
        format!("Split Subscribe — {bind_addr}"),
        SignalDirection::Output,
        channel_count,
    );

    let writers: Vec<Option<SharedWavWriter>> = if record_each_channel {
        let mut writers = Vec::with_capacity(channel_count);

        for channel_index in 0..channel_count {
            let path = generate_record_path(&format!("split_ch{channel_index}"));

            let writer = create_wav_writer(&path, 1, sample_rate).map_err(|error| {
                format!(
                    "failed to create split recording for \
                         channel {channel_index}: {error}"
                )
            })?;

            writers.push(Some(writer));
        }

        writers
    } else {
        vec![None; channel_count]
    };

    let per_channel_buffers: Vec<Arc<Mutex<VecDeque<f32>>>> = (0..channel_count)
        .map(|_| Arc::new(Mutex::new(VecDeque::new())))
        .collect();

    println!("Opening {channel_count} output device(s)...");

    let backend = get_backend();
    let mut streams = Vec::with_capacity(channel_count);
    let mut output_sample_rates = Vec::with_capacity(channel_count);

    for (channel_index, target) in device_targets.iter().enumerate() {
        let label = target
            .clone()
            .unwrap_or_else(|| "System Default".to_string());

        let (_device_label, output_config) = backend.get_output_config(target.as_deref()).map_err(|error| {
            format!("channel {channel_index} ('{label}'): {error}")
        })?;

        let output_channels = output_config.channels as usize;
        let output_sample_rate = output_config.sample_rate;
        output_sample_rates.push(output_sample_rate);

        let buffer_for_callback = per_channel_buffers[channel_index].clone();

        let signal_meter_for_callback = signal_meter.clone();
        let logical_meter_channel = channel_index;

        let stream = backend.build_output_stream(
            target.as_deref(),
            Box::new(move |data: &mut [f32]| {
                ensure_realtime_audio_thread();

                let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    let mut buffer = safe_lock(&buffer_for_callback);

                    // We ignore `output_channels` and output mono
                    // (the same sample duplicated) across all channels
                    // the device natively exposes.
                    for frame in data.chunks_mut(output_channels) {
                        let sample = buffer.pop_front().unwrap_or(0.0);
                        for out_sample in frame {
                            *out_sample = sample;
                        }
                    }

                    signal_meter_for_callback.observe_channel(logical_meter_channel, data);
                }));

                if result.is_err() {
                    eprintln!(
                        "audio-core: panic caught in split \
                         callback — outputting silence this cycle"
                    );
                    data.fill(0.0);
                    signal_meter_for_callback.observe_channel(logical_meter_channel, data);
                }
            }),
        )
        .map_err(|error| {
            format!(
                "channel {channel_index} ('{label}'): \
                 failed to build stream: {error}"
            )
        })?;

        stream
            .play()
            .map_err(|error| format!("failed to start split stream: {error}"))?;

        streams.push(stream);
    }

    demux_into_buffers(
        &per_channel_buffers,
        &writers,
        &packet_buffer[..first_packet_length],
        first_payload_offset,
        channel_count,
        sample_rate,
        &output_sample_rates,
    );

    println!("All {channel_count} channel(s) playing. Streaming...");

    let mut packets_received = 1u32;

    while keep_running.load(Ordering::Relaxed) {
        let (packet_length, _source) = match socket.recv_from(&mut packet_buffer) {
            Ok(result) => result,
            Err(ref error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                continue;
            }
            Err(ref error) if error.kind() == std::io::ErrorKind::TimedOut => {
                continue;
            }
            Err(ref error) if error.kind() == std::io::ErrorKind::ConnectionReset => {
                continue;
            }
            Err(error) => {
                return Err(format!("recv error: {error}"));
            }
        };

        let packet = &packet_buffer[..packet_length];

        let Some(parsed) = parse_packet(packet) else {
            continue;
        };

        if parsed.channel_count as usize != channel_count || parsed.sample_rate != sample_rate {
            eprintln!(
                "audio-core: split dropping packet -- \
                 format mismatch"
            );
            continue;
        }

        packets_received = packets_received.saturating_add(1);

        demux_into_buffers(
            &per_channel_buffers,
            &writers,
            packet,
            parsed.payload_offset,
            channel_count,
            sample_rate,
            &output_sample_rates,
        );

        // Keep no more than 200ms per logical channel. Dropping the
        // oldest samples prevents network or device stalls from
        // creating unbounded latency.
        for (channel_index, channel_buffer) in per_channel_buffers.iter().enumerate() {
            let maximum_samples = ((output_sample_rates[channel_index] as f64 * 0.2) as usize)
                .max(1);
            let mut buffer = safe_lock(channel_buffer);

            while buffer.len() > maximum_samples {
                buffer.pop_front();
            }
        }
    }

    // Stop callbacks before finalizing writers or dropping buffers.
    drop(streams);

    for writer in writers.iter().flatten() {
        finalize_recording(writer);
    }

    println!(
        "Done. {packets_received} packets received across \
         {channel_count} channel(s)."
    );

    Ok(())
}

/// Renders one logical mono network channel to one physical device.
///
/// The mono source is duplicated across every output channel exposed
/// by the selected device.
fn render_split_channel(
    output: &mut [f32],
    output_channels: usize,
    source_buffer: &Arc<Mutex<VecDeque<f32>>>,
) {
    if output_channels == 0 {
        output.fill(0.0);
        return;
    }

    let frame_count = output.len() / output_channels;

    let mut buffer = safe_lock(source_buffer);

    for frame_index in 0..frame_count {
        let sample = buffer.pop_front().unwrap_or(0.0).clamp(-1.0, 1.0);

        let frame_offset = frame_index * output_channels;

        for output_channel in 0..output_channels {
            output[frame_offset + output_channel] = sample;
        }
    }

    // A CPAL callback is normally frame-aligned, but explicitly clear
    // any incomplete trailing samples if a backend violates that
    // assumption.
    let rendered_samples = frame_count * output_channels;

    if rendered_samples < output.len() {
        output[rendered_samples..].fill(0.0);
    }
}

/// Demultiplexes an interleaved network payload into one mono queue per
/// logical channel.
fn demux_into_buffers(
    per_channel_buffers: &[Arc<Mutex<VecDeque<f32>>>],
    writers: &[Option<SharedWavWriter>],
    packet: &[u8],
    payload_offset: usize,
    channel_count: usize,
    input_sample_rate: u32,
    output_sample_rates: &[u32],
) {
    if channel_count == 0
        || per_channel_buffers.len() < channel_count
        || writers.len() < channel_count
        || output_sample_rates.len() < channel_count
    {
        return;
    }

    let Some(payload) = packet.get(payload_offset..) else {
        eprintln!(
            "audio-core: split dropping packet with invalid \
             payload offset"
        );
        return;
    };

    let bytes_per_frame = match channel_count.checked_mul(4) {
        Some(value) if value > 0 => value,
        _ => return,
    };

    let frame_count = payload.len() / bytes_per_frame;

    if frame_count == 0 {
        return;
    }

    // Lock each destination queue once per packet instead of once per
    // sample.
    let mut channel_samples = vec![Vec::<f32>::with_capacity(frame_count); channel_count];

    for frame_index in 0..frame_count {
        let frame_offset = frame_index * bytes_per_frame;

        for channel_index in 0..channel_count {
            let sample_offset = frame_offset + channel_index * 4;

            let sample_bytes = [
                payload[sample_offset],
                payload[sample_offset + 1],
                payload[sample_offset + 2],
                payload[sample_offset + 3],
            ];

            channel_samples[channel_index].push(f32::from_le_bytes(sample_bytes));
        }
    }

    for channel_index in 0..channel_count {
        let converted = resample_interleaved_linear(
            &channel_samples[channel_index],
            1,
            input_sample_rate,
            output_sample_rates[channel_index],
        );

        {
            let mut destination = safe_lock(&per_channel_buffers[channel_index]);

            destination.extend(converted.iter().copied());
        }

        if let Some(writer) = &writers[channel_index] {
            write_samples(writer, &channel_samples[channel_index]);
        }
    }
}
